#!/usr/bin/env python

from tests.test_utils import run
import os
import shutil

VM_NAMES = ['arthur', 'galahad']
VM_SYNCED_DIR_NAMES = ['arthur_vagrant', 'galahad_vagrant']

def reset_vagrant_dirs():
    for vagrant_dir in VM_SYNCED_DIR_NAMES:
        backup = '{}.bak'.format(vagrant_dir)
        if os.path.exists(vagrant_dir):
            if os.path.exists(backup):
                shutil.rmtree(backup)
            shutil.move(vagrant_dir, backup)
        run(['git', 'checkout', vagrant_dir])

def destroy_vms():
    run(['vagrant', 'destroy'] + VM_NAMES + ['--force'])

def main():
    destroy_vms()
    reset_vagrant_dirs()
    print(run(['vagrant', 'up']))
    print(run['./test_setup'])


if __name__ == '__main__':
    main()
